// This file is auto-generated by scripts/process-images.js. Do not edit manually.

export interface Photo {
  src: string
  alt: string
  name: string
}

export const photos: Photo[] = [
  {
    "src": "/photo_1.jpg",
    "alt": "Photo 1",
    "name": "photo_1.jpg"
  },
  {
    "src": "/photo_2.jpg",
    "alt": "Photo 2",
    "name": "photo_2.jpg"
  },
  {
    "src": "/photo_3.jpg",
    "alt": "Photo 3",
    "name": "photo_3.jpg"
  },
  {
    "src": "/photo_4.jpg",
    "alt": "Photo 4",
    "name": "photo_4.jpg"
  },
  {
    "src": "/photo_5.jpg",
    "alt": "Photo 5",
    "name": "photo_5.jpg"
  },
  {
    "src": "/photo_6.jpg",
    "alt": "Photo 6",
    "name": "photo_6.jpg"
  },
  {
    "src": "/photo_7.jpg",
    "alt": "Photo 7",
    "name": "photo_7.jpg"
  },
  {
    "src": "/photo_8.jpg",
    "alt": "Photo 8",
    "name": "photo_8.jpg"
  },
  {
    "src": "/photo_9.jpg",
    "alt": "Photo 9",
    "name": "photo_9.jpg"
  },
  {
    "src": "/photo_10.jpg",
    "alt": "Photo 10",
    "name": "photo_10.jpg"
  },
  {
    "src": "/photo_11.jpg",
    "alt": "Photo 11",
    "name": "photo_11.jpg"
  },
  {
    "src": "/photo_12.jpg",
    "alt": "Photo 12",
    "name": "photo_12.jpg"
  },
  {
    "src": "/photo_13.jpg",
    "alt": "Photo 13",
    "name": "photo_13.jpg"
  },
  {
    "src": "/photo_14.jpg",
    "alt": "Photo 14",
    "name": "photo_14.jpg"
  },
  {
    "src": "/photo_15.jpg",
    "alt": "Photo 15",
    "name": "photo_15.jpg"
  },
  {
    "src": "/photo_16.jpg",
    "alt": "Photo 16",
    "name": "photo_16.jpg"
  },
  {
    "src": "/photo_17.jpg",
    "alt": "Photo 17",
    "name": "photo_17.jpg"
  },
  {
    "src": "/photo_18.jpg",
    "alt": "Photo 18",
    "name": "photo_18.jpg"
  },
  {
    "src": "/photo_19.jpg",
    "alt": "Photo 19",
    "name": "photo_19.jpg"
  }
];
