// This file is auto-generated by scripts/process-images.js. Do not edit manually.

export interface Photo {
  src: string
  alt: string
  name: string
  gallery: string
}

export const photos: Photo[] = [
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_1.jpg",
    "alt": "dharamkot &-mcledoganj photo 1",
    "name": "photo_1.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_2.jpg",
    "alt": "dharamkot &-mcledoganj photo 2",
    "name": "photo_2.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_3.jpg",
    "alt": "dharamkot &-mcledoganj photo 3",
    "name": "photo_3.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_4.jpg",
    "alt": "dharamkot &-mcledoganj photo 4",
    "name": "photo_4.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_5.jpg",
    "alt": "dharamkot &-mcledoganj photo 5",
    "name": "photo_5.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_6.jpg",
    "alt": "dharamkot &-mcledoganj photo 6",
    "name": "photo_6.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_7.jpg",
    "alt": "dharamkot &-mcledoganj photo 7",
    "name": "photo_7.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_8.jpg",
    "alt": "dharamkot &-mcledoganj photo 8",
    "name": "photo_8.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_9.jpg",
    "alt": "dharamkot &-mcledoganj photo 9",
    "name": "photo_9.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_10.jpg",
    "alt": "dharamkot &-mcledoganj photo 10",
    "name": "photo_10.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_11.jpg",
    "alt": "dharamkot &-mcledoganj photo 11",
    "name": "photo_11.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_12.jpg",
    "alt": "dharamkot &-mcledoganj photo 12",
    "name": "photo_12.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_13.jpg",
    "alt": "dharamkot &-mcledoganj photo 13",
    "name": "photo_13.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_14.jpg",
    "alt": "dharamkot &-mcledoganj photo 14",
    "name": "photo_14.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_15.jpg",
    "alt": "dharamkot &-mcledoganj photo 15",
    "name": "photo_15.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_16.jpg",
    "alt": "dharamkot &-mcledoganj photo 16",
    "name": "photo_16.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_17.jpg",
    "alt": "dharamkot &-mcledoganj photo 17",
    "name": "photo_17.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_18.jpg",
    "alt": "dharamkot &-mcledoganj photo 18",
    "name": "photo_18.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_19.jpg",
    "alt": "dharamkot &-mcledoganj photo 19",
    "name": "photo_19.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_20.jpg",
    "alt": "dharamkot &-mcledoganj photo 20",
    "name": "photo_20.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_21.jpg",
    "alt": "dharamkot &-mcledoganj photo 21",
    "name": "photo_21.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_22.jpg",
    "alt": "dharamkot &-mcledoganj photo 22",
    "name": "photo_22.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_23.jpg",
    "alt": "dharamkot &-mcledoganj photo 23",
    "name": "photo_23.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_24.jpg",
    "alt": "dharamkot &-mcledoganj photo 24",
    "name": "photo_24.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_25.jpg",
    "alt": "dharamkot &-mcledoganj photo 25",
    "name": "photo_25.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_26.jpg",
    "alt": "dharamkot &-mcledoganj photo 26",
    "name": "photo_26.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_27.jpg",
    "alt": "dharamkot &-mcledoganj photo 27",
    "name": "photo_27.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_28.jpg",
    "alt": "dharamkot &-mcledoganj photo 28",
    "name": "photo_28.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_29.jpg",
    "alt": "dharamkot &-mcledoganj photo 29",
    "name": "photo_29.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_30.jpg",
    "alt": "dharamkot &-mcledoganj photo 30",
    "name": "photo_30.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_31.jpg",
    "alt": "dharamkot &-mcledoganj photo 31",
    "name": "photo_31.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_32.jpg",
    "alt": "dharamkot &-mcledoganj photo 32",
    "name": "photo_32.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_33.jpg",
    "alt": "dharamkot &-mcledoganj photo 33",
    "name": "photo_33.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_34.jpg",
    "alt": "dharamkot &-mcledoganj photo 34",
    "name": "photo_34.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_35.jpg",
    "alt": "dharamkot &-mcledoganj photo 35",
    "name": "photo_35.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_36.jpg",
    "alt": "dharamkot &-mcledoganj photo 36",
    "name": "photo_36.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_37.jpg",
    "alt": "dharamkot &-mcledoganj photo 37",
    "name": "photo_37.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/dharamkot-&-mcledoganj/photo_38.jpg",
    "alt": "dharamkot &-mcledoganj photo 38",
    "name": "photo_38.jpg",
    "gallery": "dharamkot-&-mcledoganj"
  },
  {
    "src": "/gallery/kerala/photo_1.jpg",
    "alt": "kerala photo 1",
    "name": "photo_1.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_2.jpg",
    "alt": "kerala photo 2",
    "name": "photo_2.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_3.jpg",
    "alt": "kerala photo 3",
    "name": "photo_3.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_4.jpg",
    "alt": "kerala photo 4",
    "name": "photo_4.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_5.jpg",
    "alt": "kerala photo 5",
    "name": "photo_5.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_6.jpg",
    "alt": "kerala photo 6",
    "name": "photo_6.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_7.jpg",
    "alt": "kerala photo 7",
    "name": "photo_7.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_8.jpg",
    "alt": "kerala photo 8",
    "name": "photo_8.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_9.jpg",
    "alt": "kerala photo 9",
    "name": "photo_9.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_10.jpg",
    "alt": "kerala photo 10",
    "name": "photo_10.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_11.jpg",
    "alt": "kerala photo 11",
    "name": "photo_11.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_12.jpg",
    "alt": "kerala photo 12",
    "name": "photo_12.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_13.jpg",
    "alt": "kerala photo 13",
    "name": "photo_13.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_14.jpg",
    "alt": "kerala photo 14",
    "name": "photo_14.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_15.jpg",
    "alt": "kerala photo 15",
    "name": "photo_15.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_16.jpg",
    "alt": "kerala photo 16",
    "name": "photo_16.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_17.jpg",
    "alt": "kerala photo 17",
    "name": "photo_17.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_18.jpg",
    "alt": "kerala photo 18",
    "name": "photo_18.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_19.jpg",
    "alt": "kerala photo 19",
    "name": "photo_19.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_20.jpg",
    "alt": "kerala photo 20",
    "name": "photo_20.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_21.jpg",
    "alt": "kerala photo 21",
    "name": "photo_21.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_22.jpg",
    "alt": "kerala photo 22",
    "name": "photo_22.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_23.jpg",
    "alt": "kerala photo 23",
    "name": "photo_23.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_24.jpg",
    "alt": "kerala photo 24",
    "name": "photo_24.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_25.jpg",
    "alt": "kerala photo 25",
    "name": "photo_25.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_26.jpg",
    "alt": "kerala photo 26",
    "name": "photo_26.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_27.jpg",
    "alt": "kerala photo 27",
    "name": "photo_27.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_28.jpg",
    "alt": "kerala photo 28",
    "name": "photo_28.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_29.jpg",
    "alt": "kerala photo 29",
    "name": "photo_29.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_30.jpg",
    "alt": "kerala photo 30",
    "name": "photo_30.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_31.jpg",
    "alt": "kerala photo 31",
    "name": "photo_31.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_32.jpg",
    "alt": "kerala photo 32",
    "name": "photo_32.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_33.jpg",
    "alt": "kerala photo 33",
    "name": "photo_33.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_34.jpg",
    "alt": "kerala photo 34",
    "name": "photo_34.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_35.jpg",
    "alt": "kerala photo 35",
    "name": "photo_35.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_36.jpg",
    "alt": "kerala photo 36",
    "name": "photo_36.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_37.jpg",
    "alt": "kerala photo 37",
    "name": "photo_37.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_38.jpg",
    "alt": "kerala photo 38",
    "name": "photo_38.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_39.jpg",
    "alt": "kerala photo 39",
    "name": "photo_39.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_40.jpg",
    "alt": "kerala photo 40",
    "name": "photo_40.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/kerala/photo_41.jpg",
    "alt": "kerala photo 41",
    "name": "photo_41.jpg",
    "gallery": "kerala"
  },
  {
    "src": "/gallery/new-delhi/photo_1.jpg",
    "alt": "new delhi photo 1",
    "name": "photo_1.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_2.jpg",
    "alt": "new delhi photo 2",
    "name": "photo_2.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_3.jpg",
    "alt": "new delhi photo 3",
    "name": "photo_3.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_4.jpg",
    "alt": "new delhi photo 4",
    "name": "photo_4.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_5.jpg",
    "alt": "new delhi photo 5",
    "name": "photo_5.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_6.jpg",
    "alt": "new delhi photo 6",
    "name": "photo_6.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_7.jpg",
    "alt": "new delhi photo 7",
    "name": "photo_7.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_8.jpg",
    "alt": "new delhi photo 8",
    "name": "photo_8.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_9.jpg",
    "alt": "new delhi photo 9",
    "name": "photo_9.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/new-delhi/photo_10.jpg",
    "alt": "new delhi photo 10",
    "name": "photo_10.jpg",
    "gallery": "new-delhi"
  },
  {
    "src": "/gallery/north-goa/photo_1.jpg",
    "alt": "north goa photo 1",
    "name": "photo_1.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_2.jpg",
    "alt": "north goa photo 2",
    "name": "photo_2.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_3.jpg",
    "alt": "north goa photo 3",
    "name": "photo_3.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_4.jpg",
    "alt": "north goa photo 4",
    "name": "photo_4.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_5.jpg",
    "alt": "north goa photo 5",
    "name": "photo_5.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_6.jpg",
    "alt": "north goa photo 6",
    "name": "photo_6.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_7.jpg",
    "alt": "north goa photo 7",
    "name": "photo_7.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_8.jpg",
    "alt": "north goa photo 8",
    "name": "photo_8.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_9.jpg",
    "alt": "north goa photo 9",
    "name": "photo_9.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_10.jpg",
    "alt": "north goa photo 10",
    "name": "photo_10.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_11.jpg",
    "alt": "north goa photo 11",
    "name": "photo_11.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_12.jpg",
    "alt": "north goa photo 12",
    "name": "photo_12.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_13.jpg",
    "alt": "north goa photo 13",
    "name": "photo_13.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_14.jpg",
    "alt": "north goa photo 14",
    "name": "photo_14.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_15.jpg",
    "alt": "north goa photo 15",
    "name": "photo_15.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_16.jpg",
    "alt": "north goa photo 16",
    "name": "photo_16.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_17.jpg",
    "alt": "north goa photo 17",
    "name": "photo_17.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_18.jpg",
    "alt": "north goa photo 18",
    "name": "photo_18.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_19.jpg",
    "alt": "north goa photo 19",
    "name": "photo_19.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_20.jpg",
    "alt": "north goa photo 20",
    "name": "photo_20.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_21.jpg",
    "alt": "north goa photo 21",
    "name": "photo_21.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_22.jpg",
    "alt": "north goa photo 22",
    "name": "photo_22.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_23.jpg",
    "alt": "north goa photo 23",
    "name": "photo_23.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_24.jpg",
    "alt": "north goa photo 24",
    "name": "photo_24.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_25.jpg",
    "alt": "north goa photo 25",
    "name": "photo_25.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_26.jpg",
    "alt": "north goa photo 26",
    "name": "photo_26.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_27.jpg",
    "alt": "north goa photo 27",
    "name": "photo_27.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_28.jpg",
    "alt": "north goa photo 28",
    "name": "photo_28.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_29.jpg",
    "alt": "north goa photo 29",
    "name": "photo_29.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_30.jpg",
    "alt": "north goa photo 30",
    "name": "photo_30.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_31.jpg",
    "alt": "north goa photo 31",
    "name": "photo_31.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_32.jpg",
    "alt": "north goa photo 32",
    "name": "photo_32.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_33.jpg",
    "alt": "north goa photo 33",
    "name": "photo_33.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_34.jpg",
    "alt": "north goa photo 34",
    "name": "photo_34.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_35.jpg",
    "alt": "north goa photo 35",
    "name": "photo_35.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_36.jpg",
    "alt": "north goa photo 36",
    "name": "photo_36.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_37.jpg",
    "alt": "north goa photo 37",
    "name": "photo_37.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_38.jpg",
    "alt": "north goa photo 38",
    "name": "photo_38.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_39.jpg",
    "alt": "north goa photo 39",
    "name": "photo_39.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_40.jpg",
    "alt": "north goa photo 40",
    "name": "photo_40.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_41.jpg",
    "alt": "north goa photo 41",
    "name": "photo_41.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_42.jpg",
    "alt": "north goa photo 42",
    "name": "photo_42.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_43.jpg",
    "alt": "north goa photo 43",
    "name": "photo_43.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_44.jpg",
    "alt": "north goa photo 44",
    "name": "photo_44.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_45.jpg",
    "alt": "north goa photo 45",
    "name": "photo_45.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_46.jpg",
    "alt": "north goa photo 46",
    "name": "photo_46.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_47.jpg",
    "alt": "north goa photo 47",
    "name": "photo_47.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_48.jpg",
    "alt": "north goa photo 48",
    "name": "photo_48.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_49.jpg",
    "alt": "north goa photo 49",
    "name": "photo_49.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_50.jpg",
    "alt": "north goa photo 50",
    "name": "photo_50.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_51.jpg",
    "alt": "north goa photo 51",
    "name": "photo_51.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_52.jpg",
    "alt": "north goa photo 52",
    "name": "photo_52.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_53.jpg",
    "alt": "north goa photo 53",
    "name": "photo_53.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/north-goa/photo_54.jpg",
    "alt": "north goa photo 54",
    "name": "photo_54.jpg",
    "gallery": "north-goa"
  },
  {
    "src": "/gallery/rishikesh/photo_1.jpg",
    "alt": "rishikesh photo 1",
    "name": "photo_1.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_2.jpg",
    "alt": "rishikesh photo 2",
    "name": "photo_2.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_3.jpg",
    "alt": "rishikesh photo 3",
    "name": "photo_3.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_4.jpg",
    "alt": "rishikesh photo 4",
    "name": "photo_4.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_5.jpg",
    "alt": "rishikesh photo 5",
    "name": "photo_5.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_6.jpg",
    "alt": "rishikesh photo 6",
    "name": "photo_6.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_7.jpg",
    "alt": "rishikesh photo 7",
    "name": "photo_7.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_8.jpg",
    "alt": "rishikesh photo 8",
    "name": "photo_8.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_9.jpg",
    "alt": "rishikesh photo 9",
    "name": "photo_9.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_10.jpg",
    "alt": "rishikesh photo 10",
    "name": "photo_10.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_11.jpg",
    "alt": "rishikesh photo 11",
    "name": "photo_11.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_12.jpg",
    "alt": "rishikesh photo 12",
    "name": "photo_12.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_13.jpg",
    "alt": "rishikesh photo 13",
    "name": "photo_13.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_14.jpg",
    "alt": "rishikesh photo 14",
    "name": "photo_14.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_15.jpg",
    "alt": "rishikesh photo 15",
    "name": "photo_15.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_16.jpg",
    "alt": "rishikesh photo 16",
    "name": "photo_16.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_17.jpg",
    "alt": "rishikesh photo 17",
    "name": "photo_17.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_18.jpg",
    "alt": "rishikesh photo 18",
    "name": "photo_18.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_19.jpg",
    "alt": "rishikesh photo 19",
    "name": "photo_19.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_20.jpg",
    "alt": "rishikesh photo 20",
    "name": "photo_20.jpg",
    "gallery": "rishikesh"
  },
  {
    "src": "/gallery/rishikesh/photo_21.jpg",
    "alt": "rishikesh photo 21",
    "name": "photo_21.jpg",
    "gallery": "rishikesh"
  }
];
