const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PUBLIC_DIR = path.join(__dirname, '..', 'public');
const LIB_DIR = path.join(__dirname, '..', 'lib');
const OUTPUT_TS = path.join(LIB_DIR, 'photography.ts');

function processImages() {
  console.log('Scanning public directory for HEIC images...');
  
  if (!fs.existsSync(PUBLIC_DIR)) {
    console.error(`Public directory does not exist at ${PUBLIC_DIR}`);
    process.exit(1);
  }

  // Clean up any previously generated IMG_*.jpg files to keep the directory clean
  const existingFiles = fs.readdirSync(PUBLIC_DIR);
  existingFiles.forEach(file => {
    if (file.startsWith('IMG_') && file.toLowerCase().endsWith('.jpg')) {
      const filePath = path.join(PUBLIC_DIR, file);
      console.log(`Cleaning up old file: ${file}`);
      fs.unlinkSync(filePath);
    }
  });

  const heicFiles = existingFiles.filter(f => f.startsWith('IMG_') && f.toLowerCase().endsWith('.heic'));
  
  // Sort HEIC files numerically/alphabetically so they get consistent sequential numbers
  heicFiles.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
  
  console.log(`Found ${heicFiles.length} HEIC files to process.`);
  
  const photoList = [];

  heicFiles.forEach((file, index) => {
    const srcPath = path.join(PUBLIC_DIR, file);
    const sequenceNumber = index + 1;
    const normalizedName = `photo_${sequenceNumber}.jpg`;
    const destPath = path.join(PUBLIC_DIR, normalizedName);
    
    // Convert HEIC to the new sequential JPG name
    if (!fs.existsSync(destPath)) {
      console.log(`Converting ${file} -> ${normalizedName}...`);
      try {
        // Use sips to convert, resize to max 1400px, and compress to quality 85
        execSync(`/usr/bin/sips -s format jpeg -s formatOptions 85 -Z 1400 "${srcPath}" --out "${destPath}"`, {
          stdio: 'inherit'
        });
        console.log(`Successfully converted ${file} to ${normalizedName}`);
      } catch (err) {
        console.error(`Failed to convert ${file}:`, err.message);
      }
    } else {
      console.log(`Skipping conversion: ${normalizedName} already exists.`);
    }

    if (fs.existsSync(destPath)) {
      photoList.push({
        src: `/${normalizedName}`,
        alt: `Photo ${sequenceNumber}`,
        name: normalizedName
      });
    }
  });

  // Generate lib/photography.ts
  console.log(`Generating metadata file at ${OUTPUT_TS}...`);
  if (!fs.existsSync(LIB_DIR)) {
    fs.mkdirSync(LIB_DIR, { recursive: true });
  }

  const fileContent = `// This file is auto-generated by scripts/process-images.js. Do not edit manually.

export interface Photo {
  src: string
  alt: string
  name: string
}

export const photos: Photo[] = ${JSON.stringify(photoList, null, 2)};
`;

  fs.writeFileSync(OUTPUT_TS, fileContent, 'utf-8');
  console.log(`Done! Registered ${photoList.length} photos.`);
}

processImages();
